name: release

on:
  workflow_run:
    workflows:
      - test
    branches: [main]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v10.2.0
        with:
          python-version: "3.12"

      - name: Build
        run: |
          uv build
          echo "RELEASE_NAME=$(uv version)" >> $GITHUB_ENV
          echo "TAG_NAME=v$(uv version --short)" >> $GITHUB_ENV
          echo "## Release notes" > NOTES.md
          sed -n '/^## /{n; :a; /^## /q; p; n; ba}' CHANGELOG.md >> NOTES.md

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          append_body: true
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          body_path: ./NOTES.md
          files: ./dist/*

      - name: Publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: uv publish
